import Sidebar from "./components/sidebar";

import "./globals.css";
import { Providers } from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body>
        <Providers>
          <div className="flex">
            <Sidebar />
            <div className="  w-screen rounded-xl  ">
              <div>{children}</div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
