import Sidebar from "./components/sidebar";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <Sidebar />
          <div className="  w-screen  bg-primary ">
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
