import Sidebar from "./components/sidebar";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en " data-theme="light">
      <body>
        <div className="flex items-start">
          <Sidebar />
          <div className="  w-screen min-h-screen bg-primary-100 p-2 ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
